export const cars = [
  {
    price: 27500,
    img: "media/images/audiNew.jpeg",
    make: "Audi",
    model: "A4",
    year: 2012,
    engine: 3.0,
    power: 220,
    mileage: 220000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 40000,
    img: "media/images/daciaNew.jpeg",
    make: "Dacia",
    model: "Sandero",
    year: 2021,
    engine: 3.0,
    power: 95,
    mileage: 23000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 30000,
    img: "media/images/skodaNew.png",
    make: "Skoda",
    model: "Octavia",
    year: 2019,
    engine: 1.4,
    power: 156,
    mileage: 45000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 6000,
    img: "media/images/fordGrandMax.jpeg",
    make: "Ford",
    model: "Grand C-Max",
    year: 2011,
    engine: 1.6,
    power: 115,
    mileage: 252000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 40000,
    img: "media/images/fiat500.jpeg",
    make: "Fiat",
    model: "500",
    year: 6000,
    engine: 1.2,
    power: 69,
    mileage: 110000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 3000,
    img: "media/images/opelCorsa.jpg",
    make: "Opel",
    model: "Corsa",
    year: 2011,
    engine: 1.3,
    power: 95,
    mileage: 230000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 27500,
    img: "media/images/audiNew.jpeg",
    make: "Audi",
    model: "A4",
    year: 2012,
    engine: 3.0,
    power: 220,
    mileage: 220000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 40000,
    img: "media/images/daciaNew.jpeg",
    make: "Dacia",
    model: "Sandero",
    year: 2021,
    engine: 3.0,
    power: 95,
    mileage: 23000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
  {
    price: 30000,
    img: "media/images/skodaNew.png",
    make: "Skoda",
    model: "Octavia",
    year: 2019,
    engine: 1.4,
    power: 156,
    mileage: 45000,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tempor orci dapibus ultrices in iaculis nunc sed augue. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Felis imperdiet proin fermentum leo vel. Ac turpis egestas integer eget aliquet nibh praesent. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Sit amet porttitor eget dolor morbi non arcu risus. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Risus viverra adipiscing at in tellus integer feugiat. Velit dignissim sodales ut eu. Volutpat ac tincidunt vitae semper. Vestibulum sed arcu non odio euismod. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Viverra justo nec ultrices dui. Turpis egestas pretium aenean pharetra magna ac placerat.`,
  },
];
// Dane do wyświetlania: cena, obrazek, marka, rok, model, rocznik, moc silnika,
// przebieg.
